dist: trusty
notifications:
  email: false
  slack: adi-labs:tCeqXPsLSyIFe3yjfWfKLRYg
  on_success: never
  on_failure: change

language: python
python:
- 3.6

addons:
  postgresql: 9.6


install:
- "./scripts/bootstrap.sh"
- pip install -U pipenv
- pipenv install --dev

before_script:
- psql --version
- pip freeze

script:
- pipenv run flake8
- pipenv run py.test --verbose --cov

before_deploy:
- openssl aes-256-cbc -K $encrypted_fff8e3f0e23f_key -iv $encrypted_fff8e3f0e23f_iv
  -in .ci/id_rsa.enc -out .ci/id_rsa -d

deploy:
  provider: script
  script: chmod +x ./scripts/deploy.sh && ./scripts/deploy.sh yes
  on:
    branch: deploy
