name: density
dependencies:
- flake8        # [test]
- flask
- gunicorn
- psycopg2
- pytest        # [test]
- python=2.7
- jupyter
- numpy
- scipy
- matplotlib
- seaborn
- pandas
- scikit-learn
- joblib
- pip:
  - Flask-Mail
  - oauth2client
