name: density
channels:
- conda-forge
- defaults
dependencies:
- bokeh
- flake8        # [test]
- flask
- gunicorn
- pandas
- psycopg2
- pytest        # [test]
- python=3.6
- pip:
  - Flask-Mail
  - oauth2client
